export const RESOURCES = {
  USER: "user",
  ROLE: "role",
  PERMISSION: "permission",
  MASTER: "master",
  MASTER_COUNTRY: "master.country",
  MASTER_REGION: "master.region",
  MASTER_CITY: "master.city",
  MASTER_DESTINATION: "master.destination",
  MASTER_HOTEL: "master.hotel",
  MASTER_AIRLINE: "master.airline",
  MASTER_TRANSPORTATION: "master.transportation",
  MASTER_FACILITY: "master.facility",
  MASTER_VISA: "master.visa",
  MASTER_CURRENCY: "master.currency",
  MASTER_PROMOTION: "master.promotion",
  MASTER_PACKAGE_CATEGORY: "master.package-category",
  MASTER_PACKAGE_TYPE: "master.package-type",
  MASTER_TAG: "master.tag",
  MASTER_BUSINESS_SETTING: "master.business-setting",
  PACKAGE: "package",
  BOOKING: "booking",
  CUSTOMER: "customer",
  JAMAAH: "jamaah",
  PAYMENT: "payment",
  INVOICE: "invoice",
  DOCUMENT: "document",
  CMS: "cms",
  MEDIA: "media",
  MARKETING: "marketing",
  LEAD: "lead",
  DASHBOARD: "dashboard",
  SETTING: "setting",
  ACTIVITY_LOG: "activity_log",
  NOTIFICATION: "notification",
  WORKFLOW: "workflow",
} as const

export const ACTIONS = {
  CREATE: "create",
  READ: "read",
  UPDATE: "update",
  DELETE: "delete",
  ALL: "all",
} as const

export type Resource = (typeof RESOURCES)[keyof typeof RESOURCES]
export type Action = (typeof ACTIONS)[keyof typeof ACTIONS]

export type PermissionString = `${Resource}:${Action}`

export const ROLE_SLUGS = {
  SUPER_ADMIN: "super-admin",
  ADMIN: "admin",
  FINANCE: "finance",
  MARKETING: "marketing",
  CS: "cs",
  MUTHOWIF: "muthowif",
  OWNER: "owner",
} as const

export type RoleSlug = (typeof ROLE_SLUGS)[keyof typeof ROLE_SLUGS]

export const ROLE_PERMISSIONS: Record<RoleSlug, PermissionString[]> = {
  [ROLE_SLUGS.SUPER_ADMIN]: [
    "user:all", "role:all", "permission:all",
    "master:all", "master.country:all", "master.region:all", "master.city:all", "master.destination:all",
    "master.hotel:all", "master.airline:all", "master.transportation:all", "master.facility:all", "master.visa:all", "master.currency:all", "master.promotion:all", "master.package-category:all", "master.package-type:all", "master.tag:all", "master.business-setting:all",
    "package:all", "booking:all",
    "customer:all", "jamaah:all", "payment:all", "invoice:all",
    "document:all", "cms:all", "media:all",
    "marketing:all", "lead:all", "dashboard:all",
    "setting:all", "activity_log:all", "notification:all",
    "workflow:all",
  ],
  [ROLE_SLUGS.ADMIN]: [
    "user:read", "role:read",
    "master:create", "master:read", "master:update", "master:delete",
    "master.country:all", "master.region:all", "master.city:all", "master.destination:all",
    "master.hotel:all", "master.airline:all", "master.transportation:all", "master.facility:all", "master.visa:all", "master.currency:all", "master.promotion:all", "master.package-category:all", "master.package-type:all", "master.tag:all", "master.business-setting:all",
    "package:create", "package:read", "package:update", "package:delete",
    "booking:create", "booking:read", "booking:update", "booking:delete",
    "customer:create", "customer:read", "customer:update",
    "jamaah:create", "jamaah:read", "jamaah:update", "jamaah:delete",
    "payment:read",
    "invoice:read",
    "document:create", "document:read", "document:update",
    "cms:create", "cms:read", "cms:update", "cms:delete",
    "media:create", "media:read", "media:update", "media:delete",
    "marketing:create", "marketing:read", "marketing:update",
    "lead:create", "lead:read", "lead:update",
    "dashboard:read",
    "activity_log:read",
    "notification:read",
  ],
  [ROLE_SLUGS.FINANCE]: [
    "payment:read", "payment:create", "payment:update",
    "invoice:read", "invoice:create", "invoice:update",
    "booking:read",
    "customer:read",
    "dashboard:read",
    "notification:read",
  ],
  [ROLE_SLUGS.MARKETING]: [
    "cms:create", "cms:read", "cms:update", "cms:delete",
    "media:create", "media:read", "media:update", "media:delete",
    "marketing:create", "marketing:read", "marketing:update", "marketing:delete",
    "dashboard:read",
    "notification:read",
  ],
  [ROLE_SLUGS.CS]: [
    "booking:create", "booking:read", "booking:update",
    "customer:create", "customer:read", "customer:update",
    "jamaah:create", "jamaah:read", "jamaah:update",
    "document:create", "document:read", "document:update",
    "lead:create", "lead:read", "lead:update",
    "payment:read",
    "package:read",
    "dashboard:read",
    "notification:read",
  ],
  [ROLE_SLUGS.MUTHOWIF]: [
    "customer:read",
    "booking:read",
    "package:read",
    "dashboard:read",
  ],
  [ROLE_SLUGS.OWNER]: [
    "dashboard:read",
    "payment:read",
    "invoice:read",
    "booking:read",
    "activity_log:read",
    "setting:read",
  ],
}
